### ISSUE TITLE
font problem!

### ISSUE THREAD

**Issue by vanderalex** [dmMaze/BallonsTranslator#570] opened 2024-09-02 07:43 UTC
the last update after [textblock refactory](https://github.com/dmMaze/BallonsTranslator/commit/94a9af6aec58191acf65a894826525e313186061) made the program completely unusable. All font settings changes are not saved! Text disappears, settings are reset, logs have constant errors:
Traceback (most recent call last):
  File "C:\AI\comics\ballons-translator\ui\mainwindow.py", line 476, in pageListCurrentItemChanged
    self.st_manager.updateSceneTextitems()
  File "C:\AI\comics\ballons-translator\ui\scenetext_manager.py", line 448, in updateSceneTextitems
    blk_item = self.addTextBlock(textblock)
  File "C:\AI\comics\ballons-translator\ui\scenetext_manager.py", line 461, in addTextBlock
    blk_item = TextBlkItem(blk, len(self.textblk_item_list), show_rect=self.canvas.textblock_mode)
  File "C:\AI\comics\ballons-translator\ui\textitem.py", line 68, in __init__
    self.initTextBlock(blk, set_format=set_format)
  File "C:\AI\comics\ballons-translator\ui\textitem.py", line 240, in initTextBlock
    self.set_fontformat(font_fmt, set_char_format=set_char_fmt, set_stroke_width=False, set_effect=False)
  File "C:\AI\comics\ballons-translator\ui\textitem.py", line 623, in set_fontformat
    alignment = [Qt.AlignmentFlag.AlignLeft, Qt.AlignmentFlag.AlignCenter, Qt.AlignmentFlag.AlignRight][ffmat.alignment]
IndexError: list index out of range

Simply switching between pages sometimes either resets the font settings or deletes the text blocks completely.

**Comment by dmMaze** [comment] 2024-09-02 09:01
The index error and font settings not saved should be fixed by https://github.com/dmMaze/BallonsTranslator/commit/b81d8cd9297f710907a5e08e2de15f37411c6d38
As for text blocks been deleted, can you try to give some instruction on how to reproduce it?

**Comment by vanderalex** [comment] 2024-09-02 09:18
After the last edits the problem with text disappearing is gone, but when you start the process (RUN button) the font name is ignored and all text areas become a different font (mine is ariel).
log:
Commit hash: <none>
[INFO   ] launch:main:184 - QT_API: pyqt6, QT Version: 6.6.1
[INFO   ] launch:main:217 - set display language to English
[INFO   ] module_manager:on_finish_setocr:902 - OCR set to google_lens
[INFO   ] module_manager:on_finish_settranslator:917 - Translator set to DeepLX API
[INFO   ] module_manager:on_finish_setdetector:896 - Text detector set to ctd
[INFO   ] module_manager:on_finish_setinpainter:909 - Inpainter set to lama_large_512px
[INFO   ] config:save_config:217 - Config saved
[INFO   ] config:save_config:217 - Config saved
[INFO   ] config:save_config:217 - Config saved
DirectWrite: CreateFontFaceFromHDC() failed (╬чэрўрхЄ ю°шсъє тю тїюфэюь Їрщых, эряЁшьхЁ т Їрщых °ЁшЇЄр.) for QFontDef(Family="System", pointsize=16, pixelsize=20, styleHint=5, weight=400, stretch=100, hintingPreference=0) LOGFONT("System", lfWidth=0, lfHeight=-20) dpi=96
DirectWrite: CreateFontFaceFromHDC() failed (╬чэрўрхЄ ю°шсъє тю тїюфэюь Їрщых, эряЁшьхЁ т Їрщых °ЁшЇЄр.) for QFontDef(Family="System", pointsize=16, pixelsize=20, styleHint=5, weight=400, stretch=100, hintingPreference=0) LOGFONT("System", lfWidth=0, lfHeight=-20) dpi=96
DirectWrite: CreateFontFaceFromHDC() failed (╬чэрўрхЄ ю°шсъє тю тїюфэюь Їрщых, эряЁшьхЁ т Їрщых °ЁшЇЄр.) for QFontDef(Family="Small Fonts", pointsize=16, pixelsize=13, styleHint=5, weight=400, stretch=100, hintingPreference=0) LOGFONT("Small Fonts", lfWidth=0, lfHeight=-13) dpi=96
DirectWrite: CreateFontFaceFromHDC() failed (╬чэрўрхЄ ю°шсъє тю тїюфэюь Їрщых, эряЁшьхЁ т Їрщых °ЁшЇЄр.) for QFontDef(Family="Small Fonts", pointsize=16, pixelsize=13, styleHint=5, weight=400, stretch=100, hintingPreference=0) LOGFONT("Small Fonts", lfWidth=0, lfHeight=-13) dpi=96
DirectWrite: CreateFontFaceFromHDC() failed (╬чэрўрхЄ ю°шсъє тю тїюфэюь Їрщых, эряЁшьхЁ т Їрщых °ЁшЇЄр.) for QFontDef(Family="Fixedsys", pointsize=16, pixelsize=20, styleHint=5, weight=400, stretch=100, hintingPreference=0) LOGFONT("Fixedsys", lfWidth=0, lfHeight=-20) dpi=96
DirectWrite: CreateFontFaceFromHDC() failed (╬чэрўрхЄ ю°шсъє тю тїюфэюь Їрщых, эряЁшьхЁ т Їрщых °ЁшЇЄр.) for QFontDef(Family="Fixedsys", pointsize=16, pixelsize=20, styleHint=5, weight=400, stretch=100, hintingPreference=0) LOGFONT("Fixedsys", lfWidth=0, lfHeight=-20) dpi=96
DirectWrite: CreateFontFaceFromHDC() failed (╬чэрўрхЄ ю°шсъє тю тїюфэюь Їрщых, эряЁшьхЁ т Їрщых °ЁшЇЄр.) for QFontDef(Family="MS Sans Serif", pointsize=16, pixelsize=20, styleHint=5, weight=400, stretch=100, hintingPreference=0) LOGFONT("MS Sans Serif", lfWidth=0, lfHeight=-20) dpi=96
DirectWrite: CreateFontFaceFromHDC() failed (╬чэрўрхЄ ю°шсъє тю тїюфэюь Їрщых, эряЁшьхЁ т Їрщых °ЁшЇЄр.) for QFontDef(Family="MS Sans Serif", pointsize=16, pixelsize=20, styleHint=5, weight=400, stretch=100, hintingPreference=0) LOGFONT("MS Sans Serif", lfWidth=0, lfHeight=-20) dpi=96
DirectWrite: CreateFontFaceFromHDC() failed (╬чэрўрхЄ ю°шсъє тю тїюфэюь Їрщых, эряЁшьхЁ т Їрщых °ЁшЇЄр.) for QFontDef(Family="MS Serif", pointsize=16, pixelsize=21, styleHint=5, weight=400, stretch=100, hintingPreference=0) LOGFONT("MS Serif", lfWidth=0, lfHeight=-21) dpi=96
DirectWrite: CreateFontFaceFromHDC() failed (╬чэрўрхЄ ю°шсъє тю тїюфэюь Їрщых, эряЁшьхЁ т Їрщых °ЁшЇЄр.) for QFontDef(Family="MS Serif", pointsize=16, pixelsize=21, styleHint=5, weight=400, stretch=100, hintingPreference=0) LOGFONT("MS Serif", lfWidth=0, lfHeight=-21) dpi=96
DirectWrite: CreateFontFaceFromHDC() failed (╬чэрўрхЄ ю°шсъє тю тїюфэюь Їрщых, эряЁшьхЁ т Їрщых °ЁшЇЄр.) for QFontDef(Family="Small Fonts", pointsize=16, pixelsize=13, styleHint=5, weight=400, stretch=100, hintingPreference=0) LOGFONT("Small Fonts", lfWidth=0, lfHeight=-13) dpi=96
DirectWrite: CreateFontFaceFromHDC() failed (╬чэрўрхЄ ю°шсъє тю тїюфэюь Їрщых, эряЁшьхЁ т Їрщых °ЁшЇЄр.) for QFontDef(Family="Small Fonts", pointsize=16, pixelsize=13, styleHint=5, weight=400, stretch=100, hintingPreference=0) LOGFONT("Small Fonts", lfWidth=0, lfHeight=-13) dpi=96
DirectWrite: CreateFontFaceFromHDC() failed (╬чэрўрхЄ ю°шсъє тю тїюфэюь Їрщых, эряЁшьхЁ т Їрщых °ЁшЇЄр.) for QFontDef(Family="System", pointsize=16, pixelsize=20, styleHint=5, weight=400, stretch=100, hintingPreference=0) LOGFONT("System", lfWidth=0, lfHeight=-20) dpi=96
DirectWrite: CreateFontFaceFromHDC() failed (╬чэрўрхЄ ю°шсъє тю тїюфэюь Їрщых, эряЁшьхЁ т Їрщых °ЁшЇЄр.) for QFontDef(Family="System", pointsize=16, pixelsize=20, styleHint=5, weight=400, stretch=100, hintingPreference=0) LOGFONT("System", lfWidth=0, lfHeight=-20) dpi=96
DirectWrite: CreateFontFaceFromHDC() failed (╬чэрўрхЄ ю°шсъє тю тїюфэюь Їрщых, эряЁшьхЁ т Їрщых °ЁшЇЄр.) for QFontDef(Family="MS Sans Serif", pointsize=16, pixelsize=20, styleHint=5, weight=400, stretch=100, hintingPreference=0) LOGFONT("MS Sans Serif", lfWidth=0, lfHeight=-20) dpi=96
DirectWrite: CreateFontFaceFromHDC() failed (╬чэрўрхЄ ю°шсъє тю тїюфэюь Їрщых, эряЁшьхЁ т Їрщых °ЁшЇЄр.) for QFontDef(Family="MS Sans Serif", pointsize=16, pixelsize=20, styleHint=5, weight=400, stretch=100, hintingPreference=0) LOGFONT("MS Sans Serif", lfWidth=0, lfHeight=-20) dpi=96
DirectWrite: CreateFontFaceFromHDC() failed (╬чэрўрхЄ ю°шсъє тю тїюфэюь Їрщых, эряЁшьхЁ т Їрщых °ЁшЇЄр.) for QFontDef(Family="MS Serif", pointsize=16, pixelsize=21, styleHint=5, weight=400, stretch=100, hintingPreference=0) LOGFONT("MS Serif", lfWidth=0, lfHeight=-21) dpi=96
DirectWrite: CreateFontFaceFromHDC() failed (╬чэрўрхЄ ю°шсъє тю тїюфэюь Їрщых, эряЁшьхЁ т Їрщых °ЁшЇЄр.) for QFontDef(Family="MS Serif", pointsize=16, pixelsize=21, styleHint=5, weight=400, stretch=100, hintingPreference=0) LOGFONT("MS Serif", lfWidth=0, lfHeight=-21) dpi=96
******************************
╬чэрўрхЄ ю°шсъє тю тїюфэюь Їрщых, эряЁшьхЁ т Їрщых °ЁшЇЄр.  ==  Indicates an error in an input file, such as a font file.

**Comment by dmMaze** [comment] 2024-09-02 11:26
> After the last edits the problem with text disappearing is gone, but when you start the process (RUN button) the font name is ignored and all text areas become a different font (mine is ariel).

You could try restart the computer and see if the problem still exists.
Besides, can you apply these fonts to text blocks in GUI manually?
And what's you ```Font Family``` setting under config panel->Typesetting? And what if you RUN in a completely (contains no project files) clean folder?

**Comment by vanderalex** [comment] 2024-09-02 12:00
the problem is reproduced for me 100% of the time. When the folder is empty - after pressing RUN the filling of balloons goes not with the selected font, but with ariel. When the text is already recognized and I press RUN again - same thing. It fills the balloons not with the selected font, but with something like ariel. After that I can apply any font to the balloon and it is applied correctly. Regardless of what font is selected on the panel - after pressing RUN the balloons are always filled with ARIEL. The old version of the program works without problems with the same fonts.

**Comment by dmMaze** [comment] 2024-09-02 13:30
> the problem is reproduced for me 100% of the time. When the folder is empty - after pressing RUN the filling of balloons goes not with the selected font, but with ariel. When the text is already recognized and I press RUN again - same thing. It fills the balloons not with the selected font, but with something like ariel. After that I can apply any font to the balloon and it is applied correctly. Regardless of what font is selected on the panel - after pressing RUN the balloons are always filled with ARIEL. The old version of the program works without problems with the same fonts.

And what's you Font Family setting under config panel->Typesetting? 
Also try delete the config.json (backup it first) 
Also make sure you're running the latest commit

**Comment by vanderalex** [comment] 2024-09-02 15:28
After I set config panel->Typesetting->Font Family -> Global setting everything started working correctly. Strange that for older versions of programs this setting has no effect. Can you describe to me the logic of this setting?
Besides, I would like to notice that the low register function (no_uppercase)  works incorrectly and leaves many sentences in lower case. 
![1](https://github.com/user-attachments/assets/2bd5ebb5-a0c3-478c-b513-d00632096918)
![2](https://github.com/user-attachments/assets/a57d53b7-8c3b-4d4b-8d5f-3db4d7255048)

**Comment by dmMaze** [comment] 2024-09-02 17:58
> After I set config panel->Typesetting->Font Family -> Global setting everything started working correctly. Strange that for older versions of programs this setting has no effect. Can you describe to me the logic of this setting?

Keep existing means RUN won't alter the font family of text blocks already on the scene unless you have title bar ->Run->detection checked, which will delete all text blocks before run. So if you start from a clean folder (with no _proj.json fiile in it), both option should apply the global format.



> Besides, I would like to notice that the low register function (no_uppercase) works incorrectly and leaves many sentences in lower case.

It only applies to the source text Google Lens spits out, and there's no post-processing for translated text, so it leaves the translator to blame.

**Comment by vanderalex** [comment] 2024-09-02 18:06
> It only applies to the source text Google Lens spits out, and there's no post-processing for translated text, so it leaves the translator to blame.

But you can see in the screenshot that it is **the source text that is not always capitalize**d at the beginning of the sentence. The problem is in the ocr_google_lens.py module - the algorithm itself does not always work correctly. I have a modified module from an old version of the program - with it all sentences start normally, with a capital letter.

**Comment by dmMaze** [comment] 2024-09-02 18:14
> I have a modified module from an old version of the program - with it all sentences start normally, with a capital letter.

You mean just replace this ocr_google_lens.py file to old one and it will work correctly? So which old file? (a link or commit hash)

**Comment by vanderalex** [comment] 2024-09-02 18:24
[ocr_google_lens.py_fix.txt](https://github.com/user-attachments/files/16840449/ocr_google_lens.py_fix.txt)
this is old ocr_google_lens.py before refactoring with new _apply_no_uppercase:

    def _apply_no_uppercase(self, text: str) -> str:
        def capitalize_first_letter(text):
            # Capitalize the first letter of each sentence
            sentences = re.split(r'(?<=[.!?вЂ¦])\s+', text.strip())
            return ' '.join(sentence.capitalize() for sentence in sentences)
        lower_text = text.lower()
        return capitalize_first_letter(lower_text)

If you need, I can provide test picture.

**Comment by dmMaze** [comment] 2024-09-02 18:28
> [ocr_google_lens.py_fix.txt](https://github.com/user-attachments/files/16840449/ocr_google_lens.py_fix.txt) this is old ocr_google_lens.py before refactoring with new _apply_no_uppercase:
> 
> ```
> def _apply_no_uppercase(self, text: str) -> str:
>     def capitalize_first_letter(text):
>         # Capitalize the first letter of each sentence
>         sentences = re.split(r'(?<=[.!?вЂ¦])\s+', text.strip())
>         return ' '.join(sentence.capitalize() for sentence in sentences)
>     lower_text = text.lower()
>     return capitalize_first_letter(lower_text)
> ```
> 
> If you need, I can provide test picture.

Try if https://github.com/dmMaze/BallonsTranslator/commit/cd4d5e2fb4d705128af3ba2deb6e1c5352d4a5dd fixs it

**Comment by vanderalex** [comment] 2024-09-02 18:56
> Try if [cd4d5e2](https://github.com/dmMaze/BallonsTranslator/commit/cd4d5e2fb4d705128af3ba2deb6e1c5352d4a5dd) fixs it

It seems everything is OK! Thanks, I'll test it more thoroughly tomorrow.

**Comment by dmMaze** [comment] 2024-09-03 05:37
I'll close it since these problems seems no longer exist, open another issue if there's new

**Closed as completed by dmMaze** 2024-09-03 05:37 UTC
