### ISSUE TITLE
Suggestion for good translator

### ISSUE THREAD

**Issue by simonrule** [dmMaze/BallonsTranslator#405] opened 2024-03-16 06:06 UTC
Can anyone suggest me the best way to translate hentai 18+ content? Which is the best translator for 18+ content?

Sorry if im not suppose to ask this questions

**Comment by bropines** [comment] 2024-03-16 06:21
> Can anyone suggest me the best way to translate hentai 18+ content? Which is the best translator for 18+ content?
> 
> Sorry if im not supposed to ask these questions

Sooner or later you would have asked that question. I use ChatGPT api(playground) and Jailbreak for it (I condemn such things of course). It's also doing pretty well deepl by api.

**Comment by bropines** [comment] 2024-03-16 06:22
And I think we'd better move this issue to discussions.

**Comment by simonrule** [comment] 2024-03-16 07:58
> > Can anyone suggest me the best way to translate hentai 18+ content? Which is the best translator for 18+ content?
> > Sorry if im not supposed to ask these questions
> 
> Sooner or later you would have asked that question. I use ChatGPT api(playground) and Jailbreak for it (I condemn such things of course). It's also doing pretty well deepl by api.


😂
Sorry i put the question in wrong section.

So far most accurate translator and give good english translation is deepl.

Is the newest chatgpt better than 3.5 version ? Or its the same at translation of course.

**Comment by bropines** [comment] 2024-03-16 08:42
> > > Can anyone suggest me the best way to translate hentai 18+ content? Which is the best translator for 18+ content?
> > > Sorry if im not supposed to ask these questions
> > 
> > 
> > Sooner or later you would have asked that question. I use ChatGPT api(playground) and Jailbreak for it (I condemn such things of course). It's also doing pretty well deepl by api.
> 
> 😂 Sorry i put the question in wrong section.
> 
> So far most accurate translator and give good english translation is deepl.
> 
> Is the newest chatgpt better than 3.5 version ? Or its the same at translation of course.

If you can get gpt4 to translate r18 content, then you will be a genius, because I couldn't)

**Comment by simonrule** [comment] 2024-03-16 08:48
> > > > Can anyone suggest me the best way to translate hentai 18+ content? Which is the best translator for 18+ content?
> > > > Sorry if im not supposed to ask these questions
> > > 
> > > 
> > > Sooner or later you would have asked that question. I use ChatGPT api(playground) and Jailbreak for it (I condemn such things of course). It's also doing pretty well deepl by api.
> > 
> > 
> > 😂 Sorry i put the question in wrong section.
> > So far most accurate translator and give good english translation is deepl.
> > Is the newest chatgpt better than 3.5 version ? Or its the same at translation of course.
> 
> If you can get gpt4 to translate r18 content, then you will be a genius, because I couldn't)

If you cannot do it then i wont be able to.

I thought sugio will be good took me hours to make it work but when i tested it was the worst for +18 contents 😂.
Seems like my best choice so far is deepl.

**Comment by bropines** [comment] 2024-03-17 22:11
If the issue is resolved, close the issue and ask such questions here
![image](https://github.com/dmMaze/BallonsTranslator/assets/57861007/b0b11ae1-6055-435d-b449-04c58d675214)

**Closed** 2024-03-18 22:32 UTC

**Comment by snakeotakon** [comment] 2024-07-07 04:31
**With Gemma 2**
A family of lightweight, state-of-the art open models built from the same research and technology used to create the Gemini models.  INFO: [https://ai.google.dev/gemma](https://ai.google.dev/gemma)


**INSTALLATION**
1. [Download the installer and install the program ollama ](https://ollama.com/) _Compatible clients ChatGPT_
2. Run prompt cmd "ollama run gemma2" 
 ` C:\Users\myuser>  ollama run gemma2`  _(Automatic Download Model  Gemma2 5GB)_
3. Configure your Translator ChatGPT
    - **Override Model**: gemma2
    - **3rd party api url**: http://localhost:11434/v1/



![ChatGPT Gemma](https://github.com/dmMaze/BallonsTranslator/assets/112669188/2bdebd0a-a6fc-44bc-93a9-9a7143af60f7)

Works with the CPU, but is highly recommended with nvidia cards. RTX-3060

_Ollama, a platform that makes local development with open-source large language models a breeze. With Ollama, everything you need to run an LLM—model weights and all of the config—is packaged into a single Modelfile_

There are a large number of models that can be tried
Meta Llama 3: The most capable openly available LLM to date
[deepseek-coder-v2](https://ollama.com/library/deepseek-coder-v2) An open-source Mixture-of-Experts code language model that achieves performance comparable to GPT4-Turbo in code-specific tasks.

https://ollama.com/library

**Comment by Qulox** [comment] 2025-02-10 22:54
In case is useful to someone:

I changed the following fields to make it work:

`chat system template:` 

```
You are a professional translation engine, please translate the text into a colloquial, elegant and fluent content, without referencing machine translations. You must only translate the text content, never interpret it. If there's any issue in the text, output the text as is.
Dont add "LET ME KNOW IF YOU HAVE ANY OTHER MANGA TRANSLATIONS YOU NEED HELP WITH!" or similar text at the end of the translation.
Translate to {to_lang}.
```

`chat sample`

```
日本語-English:
    source:
        - テレビで見た！
    target:
        - I saw it on TV!
```
